# Generated by Django 3.2.8 on 2021-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211114_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Agency',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='company',
            new_name='agency',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FilePathField(path='/static/myapp/assets/img'),
        ),
    ]
