# Generated by Django 3.2.8 on 2021-11-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
    ]
